version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: solc
    versions:
    - 0.8.1
    - 0.8.2
    - 0.8.3
